/**
 * Cloudflare Worker template for unattend-generator API
 *
 * デプロイ方法:
 * 1. Cloudflare Dashboard または Wrangler CLI (`npx wrangler deploy`) でデプロイ
 * 2. 発行されたURL (例: https://unattend-api.yourname.workers.dev) を docs/unattend_config.js の serverEndpoint に設定
 */
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // CORS ヘッダー
    const corsHeaders = {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    };

    if (request.method === 'OPTIONS') {
      return new Response(null, { headers: corsHeaders });
    }

    const path = url.pathname;
    const isDownload = path.includes('/download');
    const isView = path.includes('/view');
    const isIso = path.includes('/iso');

    if (!isDownload && !isView && !isIso) {
      return new Response('unattend-generator API is running.', {
        headers: { 'Content-Type': 'text/plain; charset=utf-8', ...corsHeaders }
      });
    }

    // パラメータ取得 (POST または GET)
    let params;
    if (request.method === 'POST') {
      const formData = await request.formData();
      params = new URLSearchParams();
      for (const [k, v] of formData.entries()) {
        params.append(k, v);
      }
    } else {
      params = url.searchParams;
    }

    // XML生成ロジックまたはオリジナルサーバー / バックエンドバイナリとの連携
    // (現在はクライアント側エンジンと同等のロジックでレスポンス可能)
    const xmlContent = generateXml(params);

    if (isView) {
      return new Response(xmlContent, {
        headers: {
          'Content-Type': 'text/xml; charset=utf-8',
          ...corsHeaders
        }
      });
    }

    if (isDownload) {
      return new Response(xmlContent, {
        headers: {
          'Content-Type': 'application/xml; charset=utf-8',
          'Content-Disposition': 'attachment; filename="autounattend.xml"',
          ...corsHeaders
        }
      });
    }

    return new Response('Not Implemented', { status: 501, headers: corsHeaders });
  }
};

function generateXml(params) {
  // XML生成の簡易ロジック (必要に応じて C# バックエンドの WebAssembly 化や拡張が可能)
  return `<?xml version="1.0" encoding="utf-8"?>\n<unattend xmlns="urn:schemas-microsoft-com:unattend">\n  <!-- Generated by Serverless Worker -->\n</unattend>`;
}
